
[introduce_yourself]
	favorite_activity = "longs walks on the beach and boning your mom"
	ign = "the_garbageman09"
	favorite_food = "Spaghetti Bolognese"
	where_youre_from = "Buttville"

[general]
	introduce_yourself = "Hello my name is the_garbageman09 but you can call me Garbo!"
	kicknotifier = "69d 4h 2m 0s"
	macro_stopper = false
	ehksdee_message = "test123"
	draw_chat_waypoints = 0
	island_macro_stopper = 0.0
	pb = "1:10"
	raider_shamer = "test123"
	kick_notifier = "Pi is an irrational number, which means that it is a real number that cannot be expressed by a simple fraction. That's because pi is what mathematicians call an \"infinite decimal\" — after the decimal point, the digits go on forever and ever."
	tentacledye_reminder = ""
	party_commands = true
	hotdog_toppings = 0

	[general.utilities]
		kicknotifier = "wtf i was kicked from skyblock?? bro wtf????? hypixel fix server bro????"
		"tentacledye_recording?" = false
		kick_notifier = 0.0
		hotdog_toppings = 0

	[general.general]
		kick_notifier = "69d 4h 2m 0s"

	[general.guild]
		pro_join_notifications = ""
		isle_of_ducks_bridge_formatter = 0.0
		bridge_formatter = ""
		pro_joined = 0.0

	[general.bridge]
		bridge_formatter = 0.0
		pro_joined = 0.0

[kuudra]

	[kuudra.buttface]
		replace_defeat_for_kuudra_down = 0.0

[custom]

	[custom."use_\"custom\"_ban_options_in_config_for_it_to_work"]
		perm_ban_or_temp = "Skill issues"
		ban_reason = "Skill issues"
		ban_time = "69d 4h 2m 0s"

[config]
	ban_time = 0

[introduction]

	[introduction.info]
		a_fun_fact_about_me_is_that = {}
		ign = "the_garbageman09"
		country = "Buttville"
		activites_you_enjoy = "Long walks on the beach"
		a_fun_fact = "My favorite food is spaghetti bolognese"
		name = "Frank Jones"
		age = "69"

